apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: standalone
spec:
  selector:
    matchLabels:
      app: standalone
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: standalone
        tier: mysql
    spec:
      containers:
        - name: standalone
          image: willmenn/standalone:0.8.3
          ports:
            - containerPort: 5555
              name: http
        - image: mysql:5.5
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              value: "auth"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "root"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim