apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: standalone
spec:
  selector:
    matchLabels:
      app: standalone
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: standalone
    spec:
      containers:
        - name: standalone
          image: willmenn/standalone:0.1
          ports:
            - containerPort: 5555
              name: http

