apiVersion: v1
kind: Service
metadata:
  name: standalone-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5555
  selector:
    app: standalone
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: standalone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi