apiVersion: v1
kind: Service
metadata:
  name: standalone
  namespace: default
spec:
  clusterIP: 10.109.205.106
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30516
      port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app: standalone
  sessionAffinity: None
  type: NodePort