version: '3'

services:
  db-mysql:
    image: mysql:5.7
    container_name: mysql_for_demo
    restart: always
    environment:
      MYSQL_DATABASE: 'auth'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - app-network
  spring-boot:
    depends_on:
      - db-mysql
      - redis
    image: willmenn/standalone:0.9.13
    container_name: demo-app
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    expose:
      - '5555'
    networks:
      - app-network
  nginx:
    depends_on:
      - spring-boot
    restart: always
    image: nginx:latest
    container_name: nginx_for_demo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
  redis:
    restart: always
    image: redis:5.0-alpine
    container_name: redis_for_demo
    volumes:
      - ./data:/data
    ports:
      - '6379:6379'

networks:
  app-network:
    driver: bridge